"use server"

import { headers } from "next/headers"
import { db } from "@/lib/db"
import { careerApplications, careerPostings } from "@/lib/db/schema"
import { eq } from "drizzle-orm"
import { verifyTurnstile } from "@/lib/security/turnstile"
import { sendEmail } from "@/lib/email/send"
import { CareerStaffNotification } from "@/lib/email/templates/CareerStaffNotification"
import { CareerCustomerReply } from "@/lib/email/templates/CareerCustomerReply"
import { createSignedDownloadUrl } from "@/lib/supabase/storage"
import * as React from "react"
import { z } from "zod"

export type CareersState =
  | { ok: true; message: string }
  | { ok: false; fieldErrors: Partial<Record<string, string[]>>; message?: string }
  | null

// ─── Resume path validator ────────────────────────────────────────────────────
// Anti-tamper: must match the path generated by /api/uploads/sign-resume
const RESUME_PATH_RE = /^resumes\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(pdf|doc|docx)$/i

const careersSchema = z.object({
  // The form posts positionId — maps to DB postingId
  positionId: z.string().min(1, "Please select a position"),
  name: z.string().min(2, "Name must be at least 2 characters").max(80, "Name must be at most 80 characters"),
  email: z.string().email("Please enter a valid email address"),
  phone: z.string().min(1, "Phone number is required"),
  link: z.string().url("Please enter a valid URL").optional().or(z.literal("")),
  availability: z
    .string()
    .min(5, "Please describe your availability (at least 5 characters)")
    .max(500, "Availability must be at most 500 characters"),
  coverLetter: z.string().max(2000, "Cover letter must be at most 2000 characters").optional(),
  consent: z.string().optional(),
  // resumePath submitted by the frontend after the direct-to-storage PUT
  resumePath: z.string().optional(),
})

export async function submitCareerApplication(
  prevState: CareersState,
  formData: FormData,
): Promise<CareersState> {
  const raw = Object.fromEntries(formData.entries())

  const parsed = careersSchema.safeParse(raw)
  if (!parsed.success) {
    return {
      ok: false,
      fieldErrors: parsed.error.flatten().fieldErrors as Partial<Record<string, string[]>>,
    }
  }

  const data = parsed.data
  const fieldErrors: Partial<Record<string, string[]>> = {}

  if (!data.consent || data.consent !== "true") {
    fieldErrors.consent = ["You must consent to be contacted"]
  }

  // Anti-tamper: validate resumePath prefix if supplied
  if (data.resumePath && !RESUME_PATH_RE.test(data.resumePath)) {
    fieldErrors.resumePath = ["Invalid resume path"]
  }

  if (Object.keys(fieldErrors).length > 0) {
    return { ok: false, fieldErrors }
  }

  // ── Turnstile verification ───────────────────────────────────────────────────
  const turnstileToken = formData.get("cf-turnstile-response")
  const headersList = await headers()
  const ip =
    headersList.get("x-forwarded-for")?.split(",")[0]?.trim() ??
    headersList.get("x-real-ip") ??
    undefined

  const turnstileOk = await verifyTurnstile(
    typeof turnstileToken === "string" ? turnstileToken : null,
    ip,
  )
  if (!turnstileOk) {
    return {
      ok: false,
      fieldErrors: {},
      message: "Bot verification failed. Please try again.",
    }
  }

  // ── Resolve posting title for emails (best-effort — non-blocking) ────────────
  let positionTitle = "Open Position"
  try {
    // positionId may be a UUID (DB posting) or a label string from the form
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.positionId)
    if (isUuid) {
      const posting = await db
        .select({ title: careerPostings.title })
        .from(careerPostings)
        .where(eq(careerPostings.id, data.positionId))
        .limit(1)
      if (posting[0]) positionTitle = posting[0].title
    } else {
      positionTitle = data.positionId
    }
  } catch {
    // Non-fatal — fall back to generic label
  }

  // ── Compose the message field from availability + coverLetter + link ─────────
  // Field mapping: form sends positionId/link/availability/coverLetter
  // DB has postingId/message — no link or availability columns.
  const messageParts: string[] = []
  messageParts.push(`Availability:\n${data.availability}`)
  if (data.coverLetter?.trim()) {
    messageParts.push(`Cover Letter:\n${data.coverLetter.trim()}`)
  }
  if (data.link?.trim()) {
    messageParts.push(`Portfolio / Link:\n${data.link.trim()}`)
  }
  const composedMessage = messageParts.join("\n\n")

  // ── DB insert — source of truth ──────────────────────────────────────────────
  try {
    await db.insert(careerApplications).values({
      postingId: /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(data.positionId)
        ? data.positionId
        : null,
      name: data.name,
      email: data.email,
      phone: data.phone?.trim() || null,
      message: composedMessage,
      resumePath: data.resumePath ?? null,
      consent: true,
      // status defaults to 'new' via DB default
    })
  } catch (err) {
    console.error("[careers] Failed to insert career application:", err)
    return {
      ok: false,
      fieldErrors: {},
      message: "Something went wrong. Please try again.",
    }
  }

  // ── Generate signed resume download URL (7-day TTL) ──────────────────────────
  let resumeDownloadUrl: string | null = null
  if (data.resumePath) {
    try {
      resumeDownloadUrl = await createSignedDownloadUrl({
        bucket: "applications",
        path: data.resumePath,
        expiresIn: 604800, // 7 days
      })
    } catch (err) {
      console.error("[careers] Failed to generate resume download URL:", err)
      // Non-fatal — email will simply omit the link
    }
  }

  // ── Emails — fire-and-forget, failure cannot fail the submit ─────────────────
  void sendEmail({
    to: process.env.RESEND_REPLY_TO ?? process.env.RESEND_FROM_EMAIL ?? "hello@districtpourhaus.com",
    subject: `New application: ${positionTitle} — ${data.name}`,
    react: React.createElement(CareerStaffNotification, {
      applicantName: data.name,
      applicantEmail: data.email,
      applicantPhone: data.phone?.trim() || null,
      positionTitle,
      message: composedMessage,
      resumeDownloadUrl,
    }),
    replyTo: data.email,
    template: "career-staff-notification",
  })

  void sendEmail({
    to: data.email,
    subject: `Application received — ${positionTitle} at District Pour Haus`,
    react: React.createElement(CareerCustomerReply, {
      applicantName: data.name,
      positionTitle,
    }),
    template: "career-customer-reply",
  })

  return {
    ok: true,
    message: "Thanks for applying. We'll be in touch if there's a match.",
  }
}
